// Code generated by protoc-gen-go. DO NOT EDIT.
// source: defi_fund.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

//storage
type BaseAccount struct {
	Available            []byte   `protobuf:"bytes,1,opt,name=Available,proto3" json:"Available,omitempty"`
	Subscribed           []byte   `protobuf:"bytes,2,opt,name=Subscribed,proto3" json:"Subscribed,omitempty"`
	Invested             []byte   `protobuf:"bytes,3,opt,name=Invested,proto3" json:"Invested,omitempty"`
	Locked               []byte   `protobuf:"bytes,4,opt,name=Locked,proto3" json:"Locked,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BaseAccount) Reset()         { *m = BaseAccount{} }
func (m *BaseAccount) String() string { return proto.CompactTextString(m) }
func (*BaseAccount) ProtoMessage()    {}
func (*BaseAccount) Descriptor() ([]byte, []int) {
	return fileDescriptor_a6187cddcbfd6af4, []int{0}
}

func (m *BaseAccount) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BaseAccount.Unmarshal(m, b)
}
func (m *BaseAccount) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BaseAccount.Marshal(b, m, deterministic)
}
func (m *BaseAccount) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BaseAccount.Merge(m, src)
}
func (m *BaseAccount) XXX_Size() int {
	return xxx_messageInfo_BaseAccount.Size(m)
}
func (m *BaseAccount) XXX_DiscardUnknown() {
	xxx_messageInfo_BaseAccount.DiscardUnknown(m)
}

var xxx_messageInfo_BaseAccount proto.InternalMessageInfo

func (m *BaseAccount) GetAvailable() []byte {
	if m != nil {
		return m.Available
	}
	return nil
}

func (m *BaseAccount) GetSubscribed() []byte {
	if m != nil {
		return m.Subscribed
	}
	return nil
}

func (m *BaseAccount) GetInvested() []byte {
	if m != nil {
		return m.Invested
	}
	return nil
}

func (m *BaseAccount) GetLocked() []byte {
	if m != nil {
		return m.Locked
	}
	return nil
}

type LoanAccount struct {
	Available            []byte   `protobuf:"bytes,1,opt,name=Available,proto3" json:"Available,omitempty"`
	Invested             []byte   `protobuf:"bytes,2,opt,name=Invested,proto3" json:"Invested,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoanAccount) Reset()         { *m = LoanAccount{} }
func (m *LoanAccount) String() string { return proto.CompactTextString(m) }
func (*LoanAccount) ProtoMessage()    {}
func (*LoanAccount) Descriptor() ([]byte, []int) {
	return fileDescriptor_a6187cddcbfd6af4, []int{1}
}

func (m *LoanAccount) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoanAccount.Unmarshal(m, b)
}
func (m *LoanAccount) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoanAccount.Marshal(b, m, deterministic)
}
func (m *LoanAccount) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoanAccount.Merge(m, src)
}
func (m *LoanAccount) XXX_Size() int {
	return xxx_messageInfo_LoanAccount.Size(m)
}
func (m *LoanAccount) XXX_DiscardUnknown() {
	xxx_messageInfo_LoanAccount.DiscardUnknown(m)
}

var xxx_messageInfo_LoanAccount proto.InternalMessageInfo

func (m *LoanAccount) GetAvailable() []byte {
	if m != nil {
		return m.Available
	}
	return nil
}

func (m *LoanAccount) GetInvested() []byte {
	if m != nil {
		return m.Invested
	}
	return nil
}

type Account struct {
	Token                []byte       `protobuf:"bytes,1,opt,name=Token,proto3" json:"Token,omitempty"`
	BaseAccount          *BaseAccount `protobuf:"bytes,2,opt,name=BaseAccount,proto3" json:"BaseAccount,omitempty"`
	LoanAccount          *LoanAccount `protobuf:"bytes,3,opt,name=LoanAccount,proto3" json:"LoanAccount,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *Account) Reset()         { *m = Account{} }
func (m *Account) String() string { return proto.CompactTextString(m) }
func (*Account) ProtoMessage()    {}
func (*Account) Descriptor() ([]byte, []int) {
	return fileDescriptor_a6187cddcbfd6af4, []int{2}
}

func (m *Account) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Account.Unmarshal(m, b)
}
func (m *Account) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Account.Marshal(b, m, deterministic)
}
func (m *Account) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Account.Merge(m, src)
}
func (m *Account) XXX_Size() int {
	return xxx_messageInfo_Account.Size(m)
}
func (m *Account) XXX_DiscardUnknown() {
	xxx_messageInfo_Account.DiscardUnknown(m)
}

var xxx_messageInfo_Account proto.InternalMessageInfo

func (m *Account) GetToken() []byte {
	if m != nil {
		return m.Token
	}
	return nil
}

func (m *Account) GetBaseAccount() *BaseAccount {
	if m != nil {
		return m.BaseAccount
	}
	return nil
}

func (m *Account) GetLoanAccount() *LoanAccount {
	if m != nil {
		return m.LoanAccount
	}
	return nil
}

type Fund struct {
	Address              []byte     `protobuf:"bytes,1,opt,name=Address,proto3" json:"Address,omitempty"`
	Accounts             []*Account `protobuf:"bytes,2,rep,name=Accounts,proto3" json:"Accounts,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Fund) Reset()         { *m = Fund{} }
func (m *Fund) String() string { return proto.CompactTextString(m) }
func (*Fund) ProtoMessage()    {}
func (*Fund) Descriptor() ([]byte, []int) {
	return fileDescriptor_a6187cddcbfd6af4, []int{3}
}

func (m *Fund) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Fund.Unmarshal(m, b)
}
func (m *Fund) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Fund.Marshal(b, m, deterministic)
}
func (m *Fund) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Fund.Merge(m, src)
}
func (m *Fund) XXX_Size() int {
	return xxx_messageInfo_Fund.Size(m)
}
func (m *Fund) XXX_DiscardUnknown() {
	xxx_messageInfo_Fund.DiscardUnknown(m)
}

var xxx_messageInfo_Fund proto.InternalMessageInfo

func (m *Fund) GetAddress() []byte {
	if m != nil {
		return m.Address
	}
	return nil
}

func (m *Fund) GetAccounts() []*Account {
	if m != nil {
		return m.Accounts
	}
	return nil
}

//newLoanEvent
type Loan struct {
	Id                   uint64   `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Address              []byte   `protobuf:"bytes,2,opt,name=Address,proto3" json:"Address,omitempty"`
	Token                []byte   `protobuf:"bytes,3,opt,name=Token,proto3" json:"Token,omitempty"`
	ShareAmount          []byte   `protobuf:"bytes,4,opt,name=ShareAmount,proto3" json:"ShareAmount,omitempty"`
	Shares               int64    `protobuf:"varint,5,opt,name=Shares,proto3" json:"Shares,omitempty"`
	Interest             []byte   `protobuf:"bytes,6,opt,name=Interest,proto3" json:"Interest,omitempty"`
	DayRate              uint64   `protobuf:"varint,7,opt,name=DayRate,proto3" json:"DayRate,omitempty"`
	SubscribeDays        uint64   `protobuf:"varint,8,opt,name=SubscribeDays,proto3" json:"SubscribeDays,omitempty"`
	ExpireDays           uint64   `protobuf:"varint,9,opt,name=ExpireDays,proto3" json:"ExpireDays,omitempty"`
	SubscribedShares     uint64   `protobuf:"varint,10,opt,name=SubscribedShares,proto3" json:"SubscribedShares,omitempty"`
	ExpireHeight         uint64   `protobuf:"varint,11,opt,name=ExpireHeight,proto3" json:"ExpireHeight,omitempty"`
	Invested             []byte   `protobuf:"bytes,12,opt,name=Invested,proto3" json:"Invested,omitempty"`
	Status               int32    `protobuf:"varint,13,opt,name=Status,proto3" json:"Status,omitempty"`
	Created              int64    `protobuf:"varint,14,opt,name=Created,proto3" json:"Created,omitempty"`
	StartTime            int64    `protobuf:"varint,15,opt,name=StartTime,proto3" json:"StartTime,omitempty"`
	Updated              int64    `protobuf:"varint,16,opt,name=Updated,proto3" json:"Updated,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Loan) Reset()         { *m = Loan{} }
func (m *Loan) String() string { return proto.CompactTextString(m) }
func (*Loan) ProtoMessage()    {}
func (*Loan) Descriptor() ([]byte, []int) {
	return fileDescriptor_a6187cddcbfd6af4, []int{4}
}

func (m *Loan) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Loan.Unmarshal(m, b)
}
func (m *Loan) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Loan.Marshal(b, m, deterministic)
}
func (m *Loan) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Loan.Merge(m, src)
}
func (m *Loan) XXX_Size() int {
	return xxx_messageInfo_Loan.Size(m)
}
func (m *Loan) XXX_DiscardUnknown() {
	xxx_messageInfo_Loan.DiscardUnknown(m)
}

var xxx_messageInfo_Loan proto.InternalMessageInfo

func (m *Loan) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Loan) GetAddress() []byte {
	if m != nil {
		return m.Address
	}
	return nil
}

func (m *Loan) GetToken() []byte {
	if m != nil {
		return m.Token
	}
	return nil
}

func (m *Loan) GetShareAmount() []byte {
	if m != nil {
		return m.ShareAmount
	}
	return nil
}

func (m *Loan) GetShares() int64 {
	if m != nil {
		return m.Shares
	}
	return 0
}

func (m *Loan) GetInterest() []byte {
	if m != nil {
		return m.Interest
	}
	return nil
}

func (m *Loan) GetDayRate() uint64 {
	if m != nil {
		return m.DayRate
	}
	return 0
}

func (m *Loan) GetSubscribeDays() uint64 {
	if m != nil {
		return m.SubscribeDays
	}
	return 0
}

func (m *Loan) GetExpireDays() uint64 {
	if m != nil {
		return m.ExpireDays
	}
	return 0
}

func (m *Loan) GetSubscribedShares() uint64 {
	if m != nil {
		return m.SubscribedShares
	}
	return 0
}

func (m *Loan) GetExpireHeight() uint64 {
	if m != nil {
		return m.ExpireHeight
	}
	return 0
}

func (m *Loan) GetInvested() []byte {
	if m != nil {
		return m.Invested
	}
	return nil
}

func (m *Loan) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *Loan) GetCreated() int64 {
	if m != nil {
		return m.Created
	}
	return 0
}

func (m *Loan) GetStartTime() int64 {
	if m != nil {
		return m.StartTime
	}
	return 0
}

func (m *Loan) GetUpdated() int64 {
	if m != nil {
		return m.Updated
	}
	return 0
}

//storage+event
type Subscription struct {
	Id                   uint64   `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	LoanId               uint64   `protobuf:"varint,2,opt,name=LoanId,proto3" json:"LoanId,omitempty"`
	Address              []byte   `protobuf:"bytes,3,opt,name=Address,proto3" json:"Address,omitempty"`
	Token                []byte   `protobuf:"bytes,4,opt,name=Token,proto3" json:"Token,omitempty"`
	ShareAmount          []byte   `protobuf:"bytes,5,opt,name=ShareAmount,proto3" json:"ShareAmount,omitempty"`
	Shares               uint64   `protobuf:"varint,6,opt,name=Shares,proto3" json:"Shares,omitempty"`
	Interest             []byte   `protobuf:"bytes,7,opt,name=Interest,proto3" json:"Interest,omitempty"`
	Status               uint64   `protobuf:"varint,8,opt,name=Status,proto3" json:"Status,omitempty"`
	Created              int64    `protobuf:"varint,9,opt,name=Created,proto3" json:"Created,omitempty"`
	Updated              int64    `protobuf:"varint,10,opt,name=Updated,proto3" json:"Updated,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Subscription) Reset()         { *m = Subscription{} }
func (m *Subscription) String() string { return proto.CompactTextString(m) }
func (*Subscription) ProtoMessage()    {}
func (*Subscription) Descriptor() ([]byte, []int) {
	return fileDescriptor_a6187cddcbfd6af4, []int{5}
}

func (m *Subscription) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Subscription.Unmarshal(m, b)
}
func (m *Subscription) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Subscription.Marshal(b, m, deterministic)
}
func (m *Subscription) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Subscription.Merge(m, src)
}
func (m *Subscription) XXX_Size() int {
	return xxx_messageInfo_Subscription.Size(m)
}
func (m *Subscription) XXX_DiscardUnknown() {
	xxx_messageInfo_Subscription.DiscardUnknown(m)
}

var xxx_messageInfo_Subscription proto.InternalMessageInfo

func (m *Subscription) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Subscription) GetLoanId() uint64 {
	if m != nil {
		return m.LoanId
	}
	return 0
}

func (m *Subscription) GetAddress() []byte {
	if m != nil {
		return m.Address
	}
	return nil
}

func (m *Subscription) GetToken() []byte {
	if m != nil {
		return m.Token
	}
	return nil
}

func (m *Subscription) GetShareAmount() []byte {
	if m != nil {
		return m.ShareAmount
	}
	return nil
}

func (m *Subscription) GetShares() uint64 {
	if m != nil {
		return m.Shares
	}
	return 0
}

func (m *Subscription) GetInterest() []byte {
	if m != nil {
		return m.Interest
	}
	return nil
}

func (m *Subscription) GetStatus() uint64 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *Subscription) GetCreated() int64 {
	if m != nil {
		return m.Created
	}
	return 0
}

func (m *Subscription) GetUpdated() int64 {
	if m != nil {
		return m.Updated
	}
	return 0
}

type Invest struct {
	Id                   uint64   `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	LoadId               uint64   `protobuf:"varint,2,opt,name=LoadId,proto3" json:"LoadId,omitempty"`
	Address              []byte   `protobuf:"bytes,3,opt,name=Address,proto3" json:"Address,omitempty"`
	LoadAmount           []byte   `protobuf:"bytes,4,opt,name=LoadAmount,proto3" json:"LoadAmount,omitempty"`
	BaseAmount           []byte   `protobuf:"bytes,5,opt,name=BaseAmount,proto3" json:"BaseAmount,omitempty"`
	BizType              int32    `protobuf:"varint,6,opt,name=BizType,proto3" json:"BizType,omitempty"`
	Beneficial           []byte   `protobuf:"bytes,7,opt,name=Beneficial,proto3" json:"Beneficial,omitempty"`
	UpdateHeight         uint64   `protobuf:"varint,8,opt,name=UpdateHeight,proto3" json:"UpdateHeight,omitempty"`
	ExpireHeight         uint64   `protobuf:"varint,9,opt,name=ExpireHeight,proto3" json:"ExpireHeight,omitempty"`
	Status               int32    `protobuf:"varint,11,opt,name=Status,proto3" json:"Status,omitempty"`
	Created              int64    `protobuf:"varint,12,opt,name=Created,proto3" json:"Created,omitempty"`
	Updated              int64    `protobuf:"varint,13,opt,name=Updated,proto3" json:"Updated,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Invest) Reset()         { *m = Invest{} }
func (m *Invest) String() string { return proto.CompactTextString(m) }
func (*Invest) ProtoMessage()    {}
func (*Invest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a6187cddcbfd6af4, []int{6}
}

func (m *Invest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Invest.Unmarshal(m, b)
}
func (m *Invest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Invest.Marshal(b, m, deterministic)
}
func (m *Invest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Invest.Merge(m, src)
}
func (m *Invest) XXX_Size() int {
	return xxx_messageInfo_Invest.Size(m)
}
func (m *Invest) XXX_DiscardUnknown() {
	xxx_messageInfo_Invest.DiscardUnknown(m)
}

var xxx_messageInfo_Invest proto.InternalMessageInfo

func (m *Invest) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Invest) GetLoadId() uint64 {
	if m != nil {
		return m.LoadId
	}
	return 0
}

func (m *Invest) GetAddress() []byte {
	if m != nil {
		return m.Address
	}
	return nil
}

func (m *Invest) GetLoadAmount() []byte {
	if m != nil {
		return m.LoadAmount
	}
	return nil
}

func (m *Invest) GetBaseAmount() []byte {
	if m != nil {
		return m.BaseAmount
	}
	return nil
}

func (m *Invest) GetBizType() int32 {
	if m != nil {
		return m.BizType
	}
	return 0
}

func (m *Invest) GetBeneficial() []byte {
	if m != nil {
		return m.Beneficial
	}
	return nil
}

func (m *Invest) GetUpdateHeight() uint64 {
	if m != nil {
		return m.UpdateHeight
	}
	return 0
}

func (m *Invest) GetExpireHeight() uint64 {
	if m != nil {
		return m.ExpireHeight
	}
	return 0
}

func (m *Invest) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *Invest) GetCreated() int64 {
	if m != nil {
		return m.Created
	}
	return 0
}

func (m *Invest) GetUpdated() int64 {
	if m != nil {
		return m.Updated
	}
	return 0
}

type SBPRegistration struct {
	InvestId              uint64   `protobuf:"varint,1,opt,name=InvestId,proto3" json:"InvestId,omitempty"`
	Name                  string   `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	ProducingAddress      []byte   `protobuf:"bytes,3,opt,name=ProducingAddress,proto3" json:"ProducingAddress,omitempty"`
	RewardWithdrawAddress []byte   `protobuf:"bytes,4,opt,name=RewardWithdrawAddress,proto3" json:"RewardWithdrawAddress,omitempty"`
	XXX_NoUnkeyedLiteral  struct{} `json:"-"`
	XXX_unrecognized      []byte   `json:"-"`
	XXX_sizecache         int32    `json:"-"`
}

func (m *SBPRegistration) Reset()         { *m = SBPRegistration{} }
func (m *SBPRegistration) String() string { return proto.CompactTextString(m) }
func (*SBPRegistration) ProtoMessage()    {}
func (*SBPRegistration) Descriptor() ([]byte, []int) {
	return fileDescriptor_a6187cddcbfd6af4, []int{7}
}

func (m *SBPRegistration) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SBPRegistration.Unmarshal(m, b)
}
func (m *SBPRegistration) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SBPRegistration.Marshal(b, m, deterministic)
}
func (m *SBPRegistration) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SBPRegistration.Merge(m, src)
}
func (m *SBPRegistration) XXX_Size() int {
	return xxx_messageInfo_SBPRegistration.Size(m)
}
func (m *SBPRegistration) XXX_DiscardUnknown() {
	xxx_messageInfo_SBPRegistration.DiscardUnknown(m)
}

var xxx_messageInfo_SBPRegistration proto.InternalMessageInfo

func (m *SBPRegistration) GetInvestId() uint64 {
	if m != nil {
		return m.InvestId
	}
	return 0
}

func (m *SBPRegistration) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *SBPRegistration) GetProducingAddress() []byte {
	if m != nil {
		return m.ProducingAddress
	}
	return nil
}

func (m *SBPRegistration) GetRewardWithdrawAddress() []byte {
	if m != nil {
		return m.RewardWithdrawAddress
	}
	return nil
}

//event
type LoanUpdate struct {
	Id                   uint64   `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	SubscribedShares     uint64   `protobuf:"varint,2,opt,name=SubscribedShares,proto3" json:"SubscribedShares,omitempty"`
	Invested             []byte   `protobuf:"bytes,3,opt,name=Invested,proto3" json:"Invested,omitempty"`
	Status               int32    `protobuf:"varint,4,opt,name=Status,proto3" json:"Status,omitempty"`
	Timestamp            int64    `protobuf:"varint,5,opt,name=Timestamp,proto3" json:"Timestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoanUpdate) Reset()         { *m = LoanUpdate{} }
func (m *LoanUpdate) String() string { return proto.CompactTextString(m) }
func (*LoanUpdate) ProtoMessage()    {}
func (*LoanUpdate) Descriptor() ([]byte, []int) {
	return fileDescriptor_a6187cddcbfd6af4, []int{8}
}

func (m *LoanUpdate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoanUpdate.Unmarshal(m, b)
}
func (m *LoanUpdate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoanUpdate.Marshal(b, m, deterministic)
}
func (m *LoanUpdate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoanUpdate.Merge(m, src)
}
func (m *LoanUpdate) XXX_Size() int {
	return xxx_messageInfo_LoanUpdate.Size(m)
}
func (m *LoanUpdate) XXX_DiscardUnknown() {
	xxx_messageInfo_LoanUpdate.DiscardUnknown(m)
}

var xxx_messageInfo_LoanUpdate proto.InternalMessageInfo

func (m *LoanUpdate) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *LoanUpdate) GetSubscribedShares() uint64 {
	if m != nil {
		return m.SubscribedShares
	}
	return 0
}

func (m *LoanUpdate) GetInvested() []byte {
	if m != nil {
		return m.Invested
	}
	return nil
}

func (m *LoanUpdate) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *LoanUpdate) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

type SubscriptionUpdate struct {
	Id                   uint64   `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Shares               uint64   `protobuf:"varint,2,opt,name=Shares,proto3" json:"Shares,omitempty"`
	Status               int32    `protobuf:"varint,3,opt,name=Status,proto3" json:"Status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SubscriptionUpdate) Reset()         { *m = SubscriptionUpdate{} }
func (m *SubscriptionUpdate) String() string { return proto.CompactTextString(m) }
func (*SubscriptionUpdate) ProtoMessage()    {}
func (*SubscriptionUpdate) Descriptor() ([]byte, []int) {
	return fileDescriptor_a6187cddcbfd6af4, []int{9}
}

func (m *SubscriptionUpdate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SubscriptionUpdate.Unmarshal(m, b)
}
func (m *SubscriptionUpdate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SubscriptionUpdate.Marshal(b, m, deterministic)
}
func (m *SubscriptionUpdate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SubscriptionUpdate.Merge(m, src)
}
func (m *SubscriptionUpdate) XXX_Size() int {
	return xxx_messageInfo_SubscriptionUpdate.Size(m)
}
func (m *SubscriptionUpdate) XXX_DiscardUnknown() {
	xxx_messageInfo_SubscriptionUpdate.DiscardUnknown(m)
}

var xxx_messageInfo_SubscriptionUpdate proto.InternalMessageInfo

func (m *SubscriptionUpdate) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *SubscriptionUpdate) GetShares() uint64 {
	if m != nil {
		return m.Shares
	}
	return 0
}

func (m *SubscriptionUpdate) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

type InvestUpdate struct {
	Id                   uint64   `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Status               uint64   `protobuf:"varint,2,opt,name=Status,proto3" json:"Status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InvestUpdate) Reset()         { *m = InvestUpdate{} }
func (m *InvestUpdate) String() string { return proto.CompactTextString(m) }
func (*InvestUpdate) ProtoMessage()    {}
func (*InvestUpdate) Descriptor() ([]byte, []int) {
	return fileDescriptor_a6187cddcbfd6af4, []int{10}
}

func (m *InvestUpdate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InvestUpdate.Unmarshal(m, b)
}
func (m *InvestUpdate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InvestUpdate.Marshal(b, m, deterministic)
}
func (m *InvestUpdate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InvestUpdate.Merge(m, src)
}
func (m *InvestUpdate) XXX_Size() int {
	return xxx_messageInfo_InvestUpdate.Size(m)
}
func (m *InvestUpdate) XXX_DiscardUnknown() {
	xxx_messageInfo_InvestUpdate.DiscardUnknown(m)
}

var xxx_messageInfo_InvestUpdate proto.InternalMessageInfo

func (m *InvestUpdate) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *InvestUpdate) GetStatus() uint64 {
	if m != nil {
		return m.Status
	}
	return 0
}

type BaseAccountUpdate struct {
	Address []byte `protobuf:"bytes,1,opt,name=Address,proto3" json:"Address,omitempty"`
	//1 deposit, 2 withdraw, 3 subscribe, 4 invest, 5 interest settle, 5 refund expire sub, 7 refund
	BizType              uint64   `protobuf:"varint,2,opt,name=BizType,proto3" json:"BizType,omitempty"`
	Amount               []byte   `protobuf:"bytes,3,opt,name=Amount,proto3" json:"Amount,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BaseAccountUpdate) Reset()         { *m = BaseAccountUpdate{} }
func (m *BaseAccountUpdate) String() string { return proto.CompactTextString(m) }
func (*BaseAccountUpdate) ProtoMessage()    {}
func (*BaseAccountUpdate) Descriptor() ([]byte, []int) {
	return fileDescriptor_a6187cddcbfd6af4, []int{11}
}

func (m *BaseAccountUpdate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BaseAccountUpdate.Unmarshal(m, b)
}
func (m *BaseAccountUpdate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BaseAccountUpdate.Marshal(b, m, deterministic)
}
func (m *BaseAccountUpdate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BaseAccountUpdate.Merge(m, src)
}
func (m *BaseAccountUpdate) XXX_Size() int {
	return xxx_messageInfo_BaseAccountUpdate.Size(m)
}
func (m *BaseAccountUpdate) XXX_DiscardUnknown() {
	xxx_messageInfo_BaseAccountUpdate.DiscardUnknown(m)
}

var xxx_messageInfo_BaseAccountUpdate proto.InternalMessageInfo

func (m *BaseAccountUpdate) GetAddress() []byte {
	if m != nil {
		return m.Address
	}
	return nil
}

func (m *BaseAccountUpdate) GetBizType() uint64 {
	if m != nil {
		return m.BizType
	}
	return 0
}

func (m *BaseAccountUpdate) GetAmount() []byte {
	if m != nil {
		return m.Amount
	}
	return nil
}

type LoanAccountUpdate struct {
	Address              []byte   `protobuf:"bytes,1,opt,name=Address,proto3" json:"Address,omitempty"`
	BizType              uint64   `protobuf:"varint,2,opt,name=BizType,proto3" json:"BizType,omitempty"`
	Amount               []byte   `protobuf:"bytes,3,opt,name=Amount,proto3" json:"Amount,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoanAccountUpdate) Reset()         { *m = LoanAccountUpdate{} }
func (m *LoanAccountUpdate) String() string { return proto.CompactTextString(m) }
func (*LoanAccountUpdate) ProtoMessage()    {}
func (*LoanAccountUpdate) Descriptor() ([]byte, []int) {
	return fileDescriptor_a6187cddcbfd6af4, []int{12}
}

func (m *LoanAccountUpdate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoanAccountUpdate.Unmarshal(m, b)
}
func (m *LoanAccountUpdate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoanAccountUpdate.Marshal(b, m, deterministic)
}
func (m *LoanAccountUpdate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoanAccountUpdate.Merge(m, src)
}
func (m *LoanAccountUpdate) XXX_Size() int {
	return xxx_messageInfo_LoanAccountUpdate.Size(m)
}
func (m *LoanAccountUpdate) XXX_DiscardUnknown() {
	xxx_messageInfo_LoanAccountUpdate.DiscardUnknown(m)
}

var xxx_messageInfo_LoanAccountUpdate proto.InternalMessageInfo

func (m *LoanAccountUpdate) GetAddress() []byte {
	if m != nil {
		return m.Address
	}
	return nil
}

func (m *LoanAccountUpdate) GetBizType() uint64 {
	if m != nil {
		return m.BizType
	}
	return 0
}

func (m *LoanAccountUpdate) GetAmount() []byte {
	if m != nil {
		return m.Amount
	}
	return nil
}

func init() {
	proto.RegisterType((*BaseAccount)(nil), "proto.BaseAccount")
	proto.RegisterType((*LoanAccount)(nil), "proto.LoanAccount")
	proto.RegisterType((*Account)(nil), "proto.Account")
	proto.RegisterType((*Fund)(nil), "proto.Fund")
	proto.RegisterType((*Loan)(nil), "proto.Loan")
	proto.RegisterType((*Subscription)(nil), "proto.Subscription")
	proto.RegisterType((*Invest)(nil), "proto.Invest")
	proto.RegisterType((*SBPRegistration)(nil), "proto.SBPRegistration")
	proto.RegisterType((*LoanUpdate)(nil), "proto.LoanUpdate")
	proto.RegisterType((*SubscriptionUpdate)(nil), "proto.SubscriptionUpdate")
	proto.RegisterType((*InvestUpdate)(nil), "proto.InvestUpdate")
	proto.RegisterType((*BaseAccountUpdate)(nil), "proto.BaseAccountUpdate")
	proto.RegisterType((*LoanAccountUpdate)(nil), "proto.LoanAccountUpdate")
}

func init() { proto.RegisterFile("defi_fund.proto", fileDescriptor_a6187cddcbfd6af4) }

var fileDescriptor_a6187cddcbfd6af4 = []byte{
	// 747 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x55, 0xcb, 0x6e, 0xd3, 0x4c,
	0x14, 0x96, 0x2f, 0xb9, 0x1d, 0xa7, 0x97, 0x7f, 0xf4, 0x53, 0x59, 0xa8, 0xaa, 0x22, 0x8b, 0x45,
	0xd4, 0x45, 0x17, 0xa5, 0x62, 0x9f, 0x52, 0x2e, 0x91, 0x2a, 0x54, 0x39, 0x41, 0x2c, 0xab, 0x49,
	0x66, 0xda, 0x8e, 0xda, 0xd8, 0x91, 0x3d, 0x69, 0x29, 0x1b, 0xb6, 0x48, 0xbc, 0x01, 0x5b, 0xde,
	0x88, 0x15, 0x8f, 0x83, 0xe6, 0x62, 0x7b, 0x06, 0xc7, 0x81, 0x05, 0xab, 0xe4, 0x3b, 0x67, 0xce,
	0x65, 0xbe, 0xf3, 0x1d, 0x0f, 0xec, 0x10, 0x7a, 0xc5, 0x2e, 0xaf, 0x56, 0x09, 0x39, 0x5a, 0x66,
	0x29, 0x4f, 0x51, 0x4b, 0xfe, 0x44, 0x9f, 0x21, 0x38, 0xc5, 0x39, 0x1d, 0xcd, 0xe7, 0xe9, 0x2a,
	0xe1, 0x68, 0x1f, 0x7a, 0xa3, 0x7b, 0xcc, 0xee, 0xf0, 0xec, 0x8e, 0x86, 0xce, 0xc0, 0x19, 0xf6,
	0xe3, 0xca, 0x80, 0x0e, 0x00, 0x26, 0xab, 0x59, 0x3e, 0xcf, 0xd8, 0x8c, 0x92, 0xd0, 0x95, 0x6e,
	0xc3, 0x82, 0x9e, 0x42, 0x77, 0x9c, 0xdc, 0xd3, 0x9c, 0x53, 0x12, 0x7a, 0xd2, 0x5b, 0x62, 0xb4,
	0x07, 0xed, 0xf3, 0x74, 0x7e, 0x4b, 0x49, 0xe8, 0x4b, 0x8f, 0x46, 0xd1, 0x1b, 0x08, 0xce, 0x53,
	0x9c, 0xfc, 0x5d, 0x03, 0x66, 0x01, 0xd7, 0x2e, 0x10, 0x7d, 0x75, 0xa0, 0x53, 0x64, 0xf9, 0x1f,
	0x5a, 0xd3, 0xf4, 0x96, 0x26, 0x3a, 0x83, 0x02, 0xe8, 0xc4, 0xba, 0xab, 0x4c, 0x10, 0x1c, 0x23,
	0xc5, 0xc7, 0x91, 0xe1, 0x89, 0x2d, 0x4a, 0x4e, 0xac, 0x06, 0xe5, 0xbd, 0xaa, 0x28, 0xc3, 0x13,
	0x9b, 0xc7, 0xa2, 0x73, 0xf0, 0x5f, 0xaf, 0x12, 0x82, 0x42, 0xe8, 0x8c, 0x08, 0xc9, 0x68, 0x9e,
	0xeb, 0x5e, 0x0a, 0x88, 0x0e, 0xa1, 0xab, 0x0f, 0xe7, 0xa1, 0x3b, 0xf0, 0x86, 0xc1, 0xf1, 0xb6,
	0x4e, 0x5a, 0x24, 0x2c, 0xfd, 0xd1, 0x0f, 0x0f, 0x7c, 0x91, 0x1d, 0x6d, 0x83, 0x3b, 0x26, 0x32,
	0x93, 0x1f, 0xbb, 0x63, 0x2b, 0xbd, 0x6b, 0xa7, 0x2f, 0x29, 0xf0, 0x4c, 0x0a, 0x06, 0x10, 0x4c,
	0x6e, 0x70, 0x46, 0x47, 0x0b, 0x79, 0x19, 0x35, 0x0a, 0xd3, 0x24, 0xe6, 0x24, 0x61, 0x1e, 0xb6,
	0x06, 0xce, 0xd0, 0x8b, 0x35, 0x52, 0xd4, 0x73, 0x9a, 0xd1, 0x9c, 0x87, 0xed, 0x82, 0x7a, 0x85,
	0x45, 0x17, 0x67, 0xf8, 0x31, 0xc6, 0x9c, 0x86, 0x1d, 0xd9, 0x5a, 0x01, 0xd1, 0x33, 0xd8, 0x2a,
	0xf5, 0x71, 0x86, 0x1f, 0xf3, 0xb0, 0x2b, 0xfd, 0xb6, 0x51, 0xe8, 0xea, 0xd5, 0xc7, 0x25, 0xcb,
	0xd4, 0x91, 0x9e, 0x3c, 0x62, 0x58, 0xd0, 0x21, 0xec, 0x56, 0x2a, 0xd3, 0xdd, 0x81, 0x3c, 0x55,
	0xb3, 0xa3, 0x08, 0xfa, 0x2a, 0xf2, 0x2d, 0x65, 0xd7, 0x37, 0x3c, 0x0c, 0xe4, 0x39, 0xcb, 0x66,
	0xc9, 0xa8, 0x5f, 0xd7, 0xe9, 0x84, 0x63, 0xbe, 0xca, 0xc3, 0xad, 0x81, 0x33, 0x6c, 0xc5, 0x1a,
	0x89, 0x3b, 0xbe, 0xcc, 0x28, 0x16, 0x21, 0xdb, 0x92, 0x98, 0x02, 0x0a, 0xc9, 0x4e, 0x38, 0xce,
	0xf8, 0x94, 0x2d, 0x68, 0xb8, 0x23, 0x7d, 0x95, 0x41, 0xc4, 0xbd, 0x5f, 0x12, 0x19, 0xb7, 0xab,
	0xe2, 0x34, 0x8c, 0xbe, 0xb8, 0xd0, 0xd7, 0xed, 0x2f, 0x39, 0x4b, 0xeb, 0xc3, 0x95, 0x2b, 0x83,
	0x93, 0xb1, 0xd2, 0xba, 0x1f, 0x6b, 0x64, 0x0e, 0xdd, 0x6b, 0x18, 0xba, 0xbf, 0x61, 0xe8, 0xad,
	0x4d, 0x43, 0x6f, 0xab, 0x4a, 0x6b, 0x86, 0xde, 0xf9, 0x6d, 0xe8, 0x15, 0x51, 0x5d, 0x1d, 0x53,
	0x23, 0xaa, 0x67, 0x13, 0x65, 0x50, 0x01, 0x36, 0x15, 0x3f, 0x5d, 0x68, 0xab, 0x09, 0x34, 0x90,
	0x40, 0x2c, 0x12, 0xc8, 0x46, 0x12, 0x0e, 0x00, 0xc4, 0x19, 0x4b, 0xe2, 0x86, 0x45, 0xf8, 0xe5,
	0x7e, 0x9b, 0x6c, 0x18, 0x16, 0x91, 0xf9, 0x94, 0x7d, 0x9a, 0x3e, 0x2e, 0xa9, 0x64, 0xa3, 0x15,
	0x17, 0x50, 0x46, 0xd2, 0x84, 0x5e, 0xb1, 0x39, 0xc3, 0x77, 0x9a, 0x10, 0xc3, 0x22, 0xb4, 0xa7,
	0x6e, 0xa4, 0xb5, 0xa7, 0x88, 0xb1, 0x6c, 0x35, 0x7d, 0xf6, 0xd6, 0xe8, 0xb3, 0xa2, 0x36, 0x68,
	0xd2, 0x60, 0xbf, 0x91, 0xda, 0x2d, 0x9b, 0xda, 0xef, 0x0e, 0xec, 0x4c, 0x4e, 0x2f, 0x62, 0x7a,
	0xcd, 0x72, 0x9e, 0x61, 0x29, 0xb4, 0x52, 0xff, 0x25, 0xd3, 0x25, 0x46, 0x08, 0xfc, 0x77, 0x78,
	0x41, 0x25, 0xdb, 0xbd, 0x58, 0xfe, 0x17, 0xfb, 0x77, 0x91, 0xa5, 0x64, 0x35, 0x67, 0xc9, 0xb5,
	0x4d, 0x7a, 0xcd, 0x8e, 0x4e, 0xe0, 0x49, 0x4c, 0x1f, 0x70, 0x46, 0x3e, 0x30, 0x7e, 0x43, 0x32,
	0xfc, 0x50, 0x04, 0xa8, 0x41, 0xac, 0x77, 0x46, 0xdf, 0x1c, 0x39, 0xb4, 0x44, 0x75, 0x5d, 0x13,
	0xc1, 0xba, 0x0f, 0x80, 0xdb, 0xf0, 0x01, 0xf8, 0xc3, 0x23, 0xa4, 0x89, 0xf5, 0x2d, 0x62, 0xf7,
	0xa1, 0x27, 0x96, 0x35, 0xe7, 0x78, 0xb1, 0xd4, 0xdf, 0xbd, 0xca, 0x10, 0x4d, 0x01, 0x99, 0x7b,
	0xda, 0xd0, 0x63, 0xb5, 0x43, 0xae, 0xb5, 0x43, 0x55, 0x4d, 0xcf, 0xac, 0x19, 0xbd, 0x80, 0xbe,
	0xea, 0x6b, 0x43, 0x3e, 0x15, 0xe7, 0x9a, 0xfb, 0x15, 0x5d, 0xc2, 0x7f, 0xc6, 0xf3, 0xa4, 0x83,
	0x9b, 0x9f, 0x19, 0x43, 0xcd, 0x2a, 0x4f, 0xa9, 0xe6, 0x3d, 0x68, 0xeb, 0x1d, 0x50, 0x34, 0x69,
	0x24, 0x0a, 0x18, 0x2f, 0xd9, 0xbf, 0x2f, 0x30, 0x6b, 0xcb, 0x67, 0xee, 0xf9, 0xaf, 0x00, 0x00,
	0x00, 0xff, 0xff, 0xcf, 0x6a, 0xf5, 0x57, 0x94, 0x08, 0x00, 0x00,
}
