// Code generated by protoc-gen-go. DO NOT EDIT.
// source: vitepb/unreceived_info.proto

package vitepb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type UnreceivedSnapshotMeta struct {
	HashHeight           *UnreceivedSnapshotMeta_SnapshotHashHeight   `protobuf:"bytes,1,opt,name=HashHeight,proto3" json:"HashHeight,omitempty"`
	UnreceivedInfos      []*UnreceivedSnapshotMeta_AddrUnreceivedInfo `protobuf:"bytes,2,rep,name=UnreceivedInfos,proto3" json:"UnreceivedInfos,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                                     `json:"-"`
	XXX_unrecognized     []byte                                       `json:"-"`
	XXX_sizecache        int32                                        `json:"-"`
}

func (m *UnreceivedSnapshotMeta) Reset()         { *m = UnreceivedSnapshotMeta{} }
func (m *UnreceivedSnapshotMeta) String() string { return proto.CompactTextString(m) }
func (*UnreceivedSnapshotMeta) ProtoMessage()    {}
func (*UnreceivedSnapshotMeta) Descriptor() ([]byte, []int) {
	return fileDescriptor_ea96b617408bdac0, []int{0}
}

func (m *UnreceivedSnapshotMeta) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UnreceivedSnapshotMeta.Unmarshal(m, b)
}
func (m *UnreceivedSnapshotMeta) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UnreceivedSnapshotMeta.Marshal(b, m, deterministic)
}
func (m *UnreceivedSnapshotMeta) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UnreceivedSnapshotMeta.Merge(m, src)
}
func (m *UnreceivedSnapshotMeta) XXX_Size() int {
	return xxx_messageInfo_UnreceivedSnapshotMeta.Size(m)
}
func (m *UnreceivedSnapshotMeta) XXX_DiscardUnknown() {
	xxx_messageInfo_UnreceivedSnapshotMeta.DiscardUnknown(m)
}

var xxx_messageInfo_UnreceivedSnapshotMeta proto.InternalMessageInfo

func (m *UnreceivedSnapshotMeta) GetHashHeight() *UnreceivedSnapshotMeta_SnapshotHashHeight {
	if m != nil {
		return m.HashHeight
	}
	return nil
}

func (m *UnreceivedSnapshotMeta) GetUnreceivedInfos() []*UnreceivedSnapshotMeta_AddrUnreceivedInfo {
	if m != nil {
		return m.UnreceivedInfos
	}
	return nil
}

type UnreceivedSnapshotMeta_SnapshotHashHeight struct {
	Hash                 []byte   `protobuf:"bytes,1,opt,name=Hash,proto3" json:"Hash,omitempty"`
	Height               uint64   `protobuf:"varint,2,opt,name=Height,proto3" json:"Height,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UnreceivedSnapshotMeta_SnapshotHashHeight) Reset() {
	*m = UnreceivedSnapshotMeta_SnapshotHashHeight{}
}
func (m *UnreceivedSnapshotMeta_SnapshotHashHeight) String() string { return proto.CompactTextString(m) }
func (*UnreceivedSnapshotMeta_SnapshotHashHeight) ProtoMessage()    {}
func (*UnreceivedSnapshotMeta_SnapshotHashHeight) Descriptor() ([]byte, []int) {
	return fileDescriptor_ea96b617408bdac0, []int{0, 0}
}

func (m *UnreceivedSnapshotMeta_SnapshotHashHeight) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UnreceivedSnapshotMeta_SnapshotHashHeight.Unmarshal(m, b)
}
func (m *UnreceivedSnapshotMeta_SnapshotHashHeight) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UnreceivedSnapshotMeta_SnapshotHashHeight.Marshal(b, m, deterministic)
}
func (m *UnreceivedSnapshotMeta_SnapshotHashHeight) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UnreceivedSnapshotMeta_SnapshotHashHeight.Merge(m, src)
}
func (m *UnreceivedSnapshotMeta_SnapshotHashHeight) XXX_Size() int {
	return xxx_messageInfo_UnreceivedSnapshotMeta_SnapshotHashHeight.Size(m)
}
func (m *UnreceivedSnapshotMeta_SnapshotHashHeight) XXX_DiscardUnknown() {
	xxx_messageInfo_UnreceivedSnapshotMeta_SnapshotHashHeight.DiscardUnknown(m)
}

var xxx_messageInfo_UnreceivedSnapshotMeta_SnapshotHashHeight proto.InternalMessageInfo

func (m *UnreceivedSnapshotMeta_SnapshotHashHeight) GetHash() []byte {
	if m != nil {
		return m.Hash
	}
	return nil
}

func (m *UnreceivedSnapshotMeta_SnapshotHashHeight) GetHeight() uint64 {
	if m != nil {
		return m.Height
	}
	return 0
}

type UnreceivedSnapshotMeta_AddrUnreceivedInfo struct {
	Address              []byte                                     `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	BalanceInfos         []*UnreceivedSnapshotMeta_TokenBalanceInfo `protobuf:"bytes,2,rep,name=BalanceInfos,proto3" json:"BalanceInfos,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                                   `json:"-"`
	XXX_unrecognized     []byte                                     `json:"-"`
	XXX_sizecache        int32                                      `json:"-"`
}

func (m *UnreceivedSnapshotMeta_AddrUnreceivedInfo) Reset() {
	*m = UnreceivedSnapshotMeta_AddrUnreceivedInfo{}
}
func (m *UnreceivedSnapshotMeta_AddrUnreceivedInfo) String() string { return proto.CompactTextString(m) }
func (*UnreceivedSnapshotMeta_AddrUnreceivedInfo) ProtoMessage()    {}
func (*UnreceivedSnapshotMeta_AddrUnreceivedInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_ea96b617408bdac0, []int{0, 1}
}

func (m *UnreceivedSnapshotMeta_AddrUnreceivedInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UnreceivedSnapshotMeta_AddrUnreceivedInfo.Unmarshal(m, b)
}
func (m *UnreceivedSnapshotMeta_AddrUnreceivedInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UnreceivedSnapshotMeta_AddrUnreceivedInfo.Marshal(b, m, deterministic)
}
func (m *UnreceivedSnapshotMeta_AddrUnreceivedInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UnreceivedSnapshotMeta_AddrUnreceivedInfo.Merge(m, src)
}
func (m *UnreceivedSnapshotMeta_AddrUnreceivedInfo) XXX_Size() int {
	return xxx_messageInfo_UnreceivedSnapshotMeta_AddrUnreceivedInfo.Size(m)
}
func (m *UnreceivedSnapshotMeta_AddrUnreceivedInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_UnreceivedSnapshotMeta_AddrUnreceivedInfo.DiscardUnknown(m)
}

var xxx_messageInfo_UnreceivedSnapshotMeta_AddrUnreceivedInfo proto.InternalMessageInfo

func (m *UnreceivedSnapshotMeta_AddrUnreceivedInfo) GetAddress() []byte {
	if m != nil {
		return m.Address
	}
	return nil
}

func (m *UnreceivedSnapshotMeta_AddrUnreceivedInfo) GetBalanceInfos() []*UnreceivedSnapshotMeta_TokenBalanceInfo {
	if m != nil {
		return m.BalanceInfos
	}
	return nil
}

type UnreceivedSnapshotMeta_TokenBalanceInfo struct {
	TokenId              []byte   `protobuf:"bytes,1,opt,name=TokenId,proto3" json:"TokenId,omitempty"`
	Number               uint64   `protobuf:"varint,2,opt,name=Number,proto3" json:"Number,omitempty"`
	Amount               []byte   `protobuf:"bytes,3,opt,name=Amount,proto3" json:"Amount,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UnreceivedSnapshotMeta_TokenBalanceInfo) Reset() {
	*m = UnreceivedSnapshotMeta_TokenBalanceInfo{}
}
func (m *UnreceivedSnapshotMeta_TokenBalanceInfo) String() string { return proto.CompactTextString(m) }
func (*UnreceivedSnapshotMeta_TokenBalanceInfo) ProtoMessage()    {}
func (*UnreceivedSnapshotMeta_TokenBalanceInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_ea96b617408bdac0, []int{0, 2}
}

func (m *UnreceivedSnapshotMeta_TokenBalanceInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UnreceivedSnapshotMeta_TokenBalanceInfo.Unmarshal(m, b)
}
func (m *UnreceivedSnapshotMeta_TokenBalanceInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UnreceivedSnapshotMeta_TokenBalanceInfo.Marshal(b, m, deterministic)
}
func (m *UnreceivedSnapshotMeta_TokenBalanceInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UnreceivedSnapshotMeta_TokenBalanceInfo.Merge(m, src)
}
func (m *UnreceivedSnapshotMeta_TokenBalanceInfo) XXX_Size() int {
	return xxx_messageInfo_UnreceivedSnapshotMeta_TokenBalanceInfo.Size(m)
}
func (m *UnreceivedSnapshotMeta_TokenBalanceInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_UnreceivedSnapshotMeta_TokenBalanceInfo.DiscardUnknown(m)
}

var xxx_messageInfo_UnreceivedSnapshotMeta_TokenBalanceInfo proto.InternalMessageInfo

func (m *UnreceivedSnapshotMeta_TokenBalanceInfo) GetTokenId() []byte {
	if m != nil {
		return m.TokenId
	}
	return nil
}

func (m *UnreceivedSnapshotMeta_TokenBalanceInfo) GetNumber() uint64 {
	if m != nil {
		return m.Number
	}
	return 0
}

func (m *UnreceivedSnapshotMeta_TokenBalanceInfo) GetAmount() []byte {
	if m != nil {
		return m.Amount
	}
	return nil
}

func init() {
	proto.RegisterType((*UnreceivedSnapshotMeta)(nil), "vitepb.UnreceivedSnapshotMeta")
	proto.RegisterType((*UnreceivedSnapshotMeta_SnapshotHashHeight)(nil), "vitepb.UnreceivedSnapshotMeta.SnapshotHashHeight")
	proto.RegisterType((*UnreceivedSnapshotMeta_AddrUnreceivedInfo)(nil), "vitepb.UnreceivedSnapshotMeta.AddrUnreceivedInfo")
	proto.RegisterType((*UnreceivedSnapshotMeta_TokenBalanceInfo)(nil), "vitepb.UnreceivedSnapshotMeta.TokenBalanceInfo")
}

func init() { proto.RegisterFile("vitepb/unreceived_info.proto", fileDescriptor_ea96b617408bdac0) }

var fileDescriptor_ea96b617408bdac0 = []byte{
	// 270 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x29, 0xcb, 0x2c, 0x49,
	0x2d, 0x48, 0xd2, 0x2f, 0xcd, 0x2b, 0x4a, 0x4d, 0x4e, 0xcd, 0x2c, 0x4b, 0x4d, 0x89, 0xcf, 0xcc,
	0x4b, 0xcb, 0xd7, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x83, 0xc8, 0x2a, 0xbd, 0x63, 0xe6,
	0x12, 0x0b, 0x85, 0xab, 0x08, 0xce, 0x4b, 0x2c, 0x28, 0xce, 0xc8, 0x2f, 0xf1, 0x4d, 0x2d, 0x49,
	0x14, 0x0a, 0xe4, 0xe2, 0xf2, 0x48, 0x2c, 0xce, 0xf0, 0x48, 0xcd, 0x4c, 0xcf, 0x28, 0x91, 0x60,
	0x54, 0x60, 0xd4, 0xe0, 0x36, 0x32, 0xd4, 0x83, 0xe8, 0xd3, 0xc3, 0xae, 0x47, 0x0f, 0xc6, 0x41,
	0x68, 0x0c, 0x42, 0x32, 0x44, 0x28, 0x9a, 0x8b, 0x1f, 0xa1, 0xd1, 0x33, 0x2f, 0x2d, 0xbf, 0x58,
	0x82, 0x49, 0x81, 0x99, 0x08, 0x73, 0x1d, 0x53, 0x52, 0x8a, 0x50, 0x75, 0x06, 0xa1, 0x9b, 0x24,
	0xe5, 0xc0, 0x25, 0x84, 0x69, 0xbd, 0x90, 0x10, 0x17, 0x0b, 0x88, 0x07, 0x76, 0x3f, 0x4f, 0x10,
	0x98, 0x2d, 0x24, 0xc6, 0xc5, 0x06, 0xf5, 0x15, 0x93, 0x02, 0xa3, 0x06, 0x4b, 0x10, 0x94, 0x27,
	0xd5, 0xcc, 0xc8, 0x25, 0x84, 0x69, 0x93, 0x90, 0x04, 0x17, 0x7b, 0x62, 0x4a, 0x4a, 0x51, 0x6a,
	0x71, 0x31, 0xd4, 0x14, 0x18, 0x57, 0x28, 0x98, 0x8b, 0xc7, 0x29, 0x31, 0x27, 0x31, 0x2f, 0x39,
	0x15, 0xd9, 0x33, 0xfa, 0x04, 0x3c, 0x13, 0x92, 0x9f, 0x9d, 0x9a, 0x87, 0xa4, 0x2f, 0x08, 0xc5,
	0x10, 0xa9, 0x18, 0x2e, 0x01, 0x74, 0x15, 0x20, 0x27, 0x80, 0xc5, 0x3c, 0x53, 0x60, 0x4e, 0x80,
	0x72, 0x41, 0x7e, 0xf1, 0x2b, 0xcd, 0x4d, 0x4a, 0x2d, 0x82, 0xf9, 0x05, 0xc2, 0x03, 0x89, 0x3b,
	0xe6, 0xe6, 0x97, 0xe6, 0x95, 0x48, 0x30, 0x83, 0x35, 0x40, 0x79, 0x49, 0x6c, 0xe0, 0xf8, 0x37,
	0x06, 0x04, 0x00, 0x00, 0xff, 0xff, 0x7c, 0xcd, 0xa8, 0x21, 0x1f, 0x02, 0x00, 0x00,
}
